---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    driver_config:
      network:
        - ["private_network", {ip: "33.33.33.10"}]
    run_list:
      - recipe[chef-graphite::default]
    attributes:
